CREATE TABLE booths
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booth_number VARCHAR(255)                            NOT NULL,
    x            INTEGER                                 NOT NULL,
    y            INTEGER                                 NOT NULL,
    width        INTEGER                                 NOT NULL,
    height       INTEGER                                 NOT NULL,
    price        INTEGER                                 NOT NULL,
    size         VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    company      VARCHAR(255),
    CONSTRAINT pk_booths PRIMARY KEY (id)
);

CREATE TABLE reservation_services
(
    reservation_id BIGINT NOT NULL,
    service_id     BIGINT NOT NULL
);

CREATE TABLE reservations
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booth_id                BIGINT                                  NOT NULL,
    company_name            VARCHAR(255)                            NOT NULL,
    industry                VARCHAR(255),
    website                 VARCHAR(255),
    contact_name            VARCHAR(255)                            NOT NULL,
    contact_email           VARCHAR(255)                            NOT NULL,
    contact_phone           VARCHAR(255)                            NOT NULL,
    total_amount            INTEGER                                 NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    agreed_to_terms         BOOLEAN                                 NOT NULL,
    agreed_to_participation BOOLEAN                                 NOT NULL,
    agreed_to_conditions    BOOLEAN                                 NOT NULL,
    invoice_company_name    VARCHAR(255),
    invoice_address         VARCHAR(255),
    invoice_nip             VARCHAR(255),
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

CREATE TABLE services
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    service_code VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  TEXT,
    price        INTEGER                                 NOT NULL,
    vat          INTEGER                                 NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    is_logged_in  BOOLEAN                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_login_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE booths
    ADD CONSTRAINT uc_booths_boothnumber UNIQUE (booth_number);

ALTER TABLE reservations
    ADD CONSTRAINT uc_reservations_contactemail UNIQUE (contact_email);

ALTER TABLE services
    ADD CONSTRAINT uc_services_servicecode UNIQUE (service_code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_BOOTH FOREIGN KEY (booth_id) REFERENCES booths (id);

ALTER TABLE reservation_services
    ADD CONSTRAINT fk_resser_on_additional_service FOREIGN KEY (service_id) REFERENCES services (id);

ALTER TABLE reservation_services
    ADD CONSTRAINT fk_resser_on_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id);